In [2]:
import numpy as np
arr1=np.random.randint(100,500,(30,5))
print(arr1)
avg=np.sum(arr1, axis=0)/30
print("Average stock prices:",avg)
print("Highest price recorded: ",arr1.max(),"at Day")
for i in range(0,len(arr1)):
    for j in range(0,len(arr1[i])):
        normalized_prices = (arr1[j] - arr1.min()) / (arr1.max() - arr1.min())
print("Normalized prices:", normalized_prices)

[[353 389 113 362 358]
 [258 346 229 361 383]
 [118 376 334 355 147]
 [480 326 445 498 323]
 [361 400 493 158 419]
 [480 494 478 204 310]
 [211 234 245 451 483]
 [104 283 267 190 362]
 [175 451 360 223 283]
 [494 388 385 210 346]
 [423 346 371 388 338]
 [375 226 203 101 467]
 [490 307 351 290 479]
 [454 347 103 218 490]
 [303 396 357 262 339]
 [107 439 497 447 201]
 [410 310 238 182 408]
 [460 355 357 103 367]
 [224 274 173 331 213]
 [145 189 398 484 265]
 [323 281 196 167 338]
 [225 391 499 443 223]
 [108 394 459 203 360]
 [223 347 279 338 240]
 [115 405 169 123 242]
 [202 199 187 231 399]
 [173 140 426 461 469]
 [300 413 115 267 199]
 [359 472 414 206 485]
 [136 265 134 256 460]]
Average stock prices: [286.3        339.43333333 309.16666667 283.76666667 346.53333333]
Highest price recorded:  499 at Day
Normalized prices: [0.65326633 0.75125628 0.98492462 0.14321608 0.79899497]
